### PR TITLE
Fix for invalid concatenated path causing install to fail in OpenBazaar

### PR DESCRIPTION
**Pull request by sammiejenkins**
This fixes an issue when trying to install the latest version of OpenBazaar

### CODE REVIEW

**Comment by kalikaneko** [comment]
thanks for reporting @sammiejenkins  
just merged (the fix was in master but not in develop)

**Comment by yagoulas** [comment]
Is there any plan to update the version hosted in pypi? Right now the latest version is 2.6.3-1 which still doesn't use the safe url.

**Comment by dionyziz** [comment]
This is critical for our deployment purposes and breaks our build for OpenBazaar. If this does't get on pypi, we have to host pysqlcipher ourselves.

**Comment by kalikaneko** [comment]
@yagoulas @dionyziz this fix is already in pypi since november or so:  pip install pysqlcipher==2.6.4
I think I forgot to make it the default one. Can you confirm that 2.6.4 is working for you? I'll make it the default release after a confirmation on osx.

**Comment by kalikaneko** [comment]
thanks @sammiejenkins! I'll wait for @dionyziz or somebody else confirmation on osx. If I get no notice in a couple of days I'll make it the default release, and we'll see if something breaks :)

**Comment by dionyziz** [comment]
Works for me on mac.

**Comment by kalikaneko** [comment]
@dionyziz thanks for testing! I've just made it the default release.

**Pull request merged**
